### ISSUE TITLE
yajl-ruby high severity security vulnerability

### ISSUE THREAD

**Issue by stevemoser** [netlify-templates/jekyll-netlify-cms#13]
I found this warning message after forking the repo.

    We found a potential security vulnerability in one of your dependencies.
    The yajl-ruby dependency defined in Gemfile.lock has a known high severity security vulnerability in version range < 1.3.1 and should be updated.

**Comment by erquhart** [comment]
Would definitely take a PR for this. I spent some time trying to get a patch up, but I'm having major issues with Ruby package management (specifically getting ffi to install, even after following all of the solutions I could find).

cc/ @calavera

**Comment by erquhart** [comment]
Fixed in #20.
