### ISSUE TITLE
Error displaying images after upload

### ISSUE THREAD

**Issue by tinykite** [netlify-templates/jekyll-netlify-cms#24]
When I try to upload images in the CMS, after using the one-click deploy with Netlify button, I initially get the following error: "Failed to persist media: API_Error" 

In the console, the problem is always listed as a 401 GET error, with one of two error messages:

"This endpoint requires a Bearer token"  
"Access to endpoint not allowed: this part of Github's API has been restricted"

The images appear to be successfully uploading to the [git repo](http://github.com/tinykite/dummy-repo). After the image upload triggers a new deploy of the website, the images also show up in the media gallery on the backend/admin view of the [website](http://romantic-saha-1cfe46.netlify.com). 

![screen shot 2018-04-08 at 5 40 15 pm](https://user-images.githubusercontent.com/4039311/38473591-057c2fe0-3b58-11e8-963f-cb1451ec8ca4.png)

**Comment by erquhart** [comment]
This was fixed in netlify/netlify-cms#1221, released in [1.5.0](https://github.com/netlify/netlify-cms/releases/tag/1.5.0).
