### ISSUE TITLE
Using the button "Deploy to Netlify" fails

### ISSUE THREAD

**Issue by ruvido** [netlify-templates/jekyll-netlify-cms#31]
I am registered to Netlify and run several websites there.

I attempted to use the deploy, followed the procedure. Once I am on netlify website, the build fails. Going back to github it shows that the newly created repo is empty.

**Comment by erquhart** [comment]
The repository contents are pushed after the build completes when using Deploy to Netlify, so if the build fails, the repo remains empty. Looking into the failure now.

**Comment by erquhart** [comment]
Caused by https://github.com/ruby-concurrency/concurrent-ruby/issues/768
