### ISSUE TITLE
netlify-identity-widget.js 404

### ISSUE THREAD

**Issue by JackGilmore** [netlify-templates/jekyll-netlify-cms#35]
`netlify-identity-widget.js` doesn't appear to be hosted at https://identity-js.netlify.com/v1/netlify-identity-widget.js anymore and produces a 404. 

I was able to get this working again by swapping in https://identity.netlify.com/v1/netlify-identity-widget.js to use instead

**Comment by martinjagodic** [comment]
@JackGilmore do you mind opening a PR and replace the path in this template?

**Comment by JackGilmore** [comment]
@martinjagodic Opened a PR to solve this in #36
